### ISSUE TITLE
Permission to use your library

### ISSUE THREAD

**Issue by manasdebashiskar** [pleira/sgp4s#1]
Hi, 
 I would like to use the satellite TLE library in my code. 
 Also I would like to be able to give the time of the satellite and know the satellite location at that time. Can you please give me some guidance?

Thanks in advance.
..Manas

**Comment by pleira** [comment]
Manas,

No problem to use the library. I have set the license to Apache 2.0. 

Regarding the use case you have, you need the TLE, and then propagate the orbit a number of minutes with respect the date from the TLE to calculate the new Position and Velocity coordinates which are in the TEME reference frame (a special frame used for TLE data). 

I would recommend as well looking into the Orekit project for doing your calculations.
